Server side
noordean/inverted-index-api pull request #3
Opened 2017-05-08 15:37 UTC by noordean

2017-05-08 16:56 UTC, ngfizzy reviewed
88% . Nice one.  You can as well try not to push your coverage file. Generally, auto generated files should not be pushed to github

2017-05-08 16:59 UTC, victor-gesit reviewed
Take a look at the issues I highlighted and fix them, or reply with your explanations.

2017-05-08 16:59 UTC, victor4l commented on coverage/lcov-report/index.html
>      </h1>
You're not supposed to upload your coverage folder to git.

2017-05-08 16:59 UTC, victor4l commented on dist/route/route.js
> +    if (req.body.searchTerms.length === 0) {
Validation shouldn't be done in the route.

2017-05-08 16:59 UTC, victor4l commented on dist/tests/inverted-index-test.js
> +  'book1.json': {
It would be better if you could move all these into an external file and then import the variables.

2017-05-08 16:59 UTC, victor4l commented on route/route.js
> +    if (req.body.searchTerms.length === 0) {
Validation should be separated from the route

2017-05-08 16:59 UTC, victor4l commented on tests/inverted-index-test.js
> +  'book1.json': {
These files for testing should be put into an external file and imported into the test suite.

2017-05-08 17:36 UTC, noordean commented on coverage/lcov-report/index.html
>      </h1>
Thanks i will correct that

2017-05-08 17:36 UTC, noordean commented on dist/route/route.js
> +    if (req.body.searchTerms.length === 0) {
Alright i will find a way of validating from my class

2017-05-08 17:38 UTC, noordean commented on dist/tests/inverted-index-test.js
> +  'book1.json': {
I was thinking of something like that but forgot to implement it. Thanks i will definitely implement it

2017-05-08 17:39 UTC, noordean commented on tests/inverted-index-test.js
> +  'book1.json': {
Yeah i will

2017-05-09 09:35 UTC, nelsonabienorin commented on coverage/lcov-report/index.html
>      </h1>
Have you corrected that?

2017-05-09 09:35 UTC, nelsonabienorin commented on dist/gulpfile.babel.js
Why do you need to bundle your gulp.babel.js here?

2017-05-09 09:35 UTC, nelsonabienorin commented on dist/route/route.js
>  var search = (0, _multer2.default)(); // This is used for search endpoint since no uploading is involved
Bundling all the files separately will not fully optimize the memory and speed of your app,  bundling into just one file will be advised.

2017-05-09 09:59 UTC, ngfizzy commented on tests/inverted-index-test.js
> +const createdIndexForBook1 = {
this variable is taking to many lines. you can try to minimize the number of lines it takes by putting your arrays on single line. 

for example. use `for: [0,1]`

2017-05-09 12:42 UTC, nelsonabienorin approved these changes
Good work done so far but kindly apply all the requested changes and reply where necessary.

2017-05-09 12:42 UTC, andela-nrotimi commented on src/inverted-index.js
>      if (fileName.match('.json$') === null) {
what does the $ symbol at the end of .json does?

2017-05-09 12:42 UTC, andela-nrotimi commented on src/inverted-index.js
>          for (const key in fileContent[i]) {
A more descriptive variable name can be used other than key

2017-05-09 12:42 UTC, andela-nrotimi commented on src/inverted-index.js
>            const getEachKey = fileContent[i][key].toLowerCase().replace(/\W+/g, ' ').split(' ');
A more descriptive variable name can be used

2017-05-09 12:42 UTC, andela-nrotimi commented on src/inverted-index.js
> +            for (const keyy in fileContent[l]) {
keyy ? Why is this used as a variable name and also why do you use const?

2017-05-09 12:42 UTC, andela-nrotimi commented on src/inverted-index.js
>          getSearchTerms.push(...fileName); // definitly the second arg is seachTerms
change definitly to definitely

2017-05-09 12:42 UTC, andela-nrotimi commented on tests/inverted-index-test.js
>  import indexObj from '../src/inverted-index';
whats indexObj? Can the name be more descriptive?

2017-05-09 12:42 UTC, andela-nrotimi commented on tests/inverted-index-test.js
Apart from testing for a json array, you should also test for an empty json array

2017-05-09 12:42 UTC, andela-nrotimi commented on tests/inverted-index-test.js
> +
Where is the test for an Invalid file?

2017-05-09 12:42 UTC, andela-nrotimi commented on tests/inverted-index-test.js
> +
I can't find the test for "Ensure passed in index is in the valid format"

2017-05-09 12:42 UTC, andela-nrotimi commented on tests/inverted-index-test.js
> +  it('should return correct result if both fileName and searchTerms are supplied', (done) => {
Can't find the test for "Ensures index returns the correct results when searched"

2017-05-09 12:42 UTC, andela-nrotimi commented on tests/inverted-index-test.js
> +        });
Can't find test that "Ensure searchIndex can handle an array of search terms"

2017-05-09 12:42 UTC, andela-nrotimi commented on tests/inverted-index-test.js
> +
Can't find test that "Ensure searchIndex can handle a varied number of search terms as arguments"

2017-05-09 12:42 UTC, andela-nrotimi commented on tests/super-test.js
> -import supertest from 'supertest';
What's the essence of this file in your test?

2017-05-09 14:54 UTC, noordean commented on dist/gulpfile.babel.js
It was actually a mistake. It's been corrected

2017-05-09 14:55 UTC, noordean commented on dist/route/route.js
>  var search = (0, _multer2.default)(); // This is used for search endpoint since no uploading is involved
It's been corrected

2017-05-09 14:55 UTC, noordean commented on tests/inverted-index-test.js
> +const createdIndexForBook1 = {
Thanks. Implemented

2017-05-09 14:58 UTC, noordean commented on src/inverted-index.js
>      if (fileName.match('.json$') === null) {
The $ helps check for a value at the end of a certain string, so it enables me to check for '.json' at the  end of a file name

2017-05-09 14:58 UTC, noordean commented on src/inverted-index.js
>          for (const key in fileContent[i]) {
I had already refactored this

2017-05-09 14:59 UTC, noordean commented on src/inverted-index.js
>            const getEachKey = fileContent[i][key].toLowerCase().replace(/\W+/g, ' ').split(' ');
Done

2017-05-09 14:59 UTC, noordean commented on src/inverted-index.js
> +            for (const keyy in fileContent[l]) {
Already refactored

2017-05-09 14:59 UTC, noordean commented on src/inverted-index.js
>          getSearchTerms.push(...fileName); // definitly the second arg is seachTerms
Done

2017-05-09 15:00 UTC, noordean commented on tests/inverted-index-test.js
>  import indexObj from '../src/inverted-index';
It's been changed to InvertedIndexObject

2017-05-09 15:00 UTC, noordean commented on tests/inverted-index-test.js
This has been implemented

2017-05-09 17:46 UTC, noordean commented on tests/inverted-index-test.js
> +        });
It's been included

2017-05-09 17:47 UTC, noordean commented on tests/super-test.js
> -import supertest from 'supertest';
It has been removed. It's no more needed

2017-05-09 20:48 UTC, noordean commented on dist/route/route.js
>  var search = (0, _multer2.default)(); // This is used for search endpoint since no uploading is involved
You mean i actually transpile all the files into a single file??

2017-05-10 16:40 UTC, Seyi-Keye requested changes

2017-05-10 16:40 UTC, andela-oaromokeye commented on README.md
> +Note: [-1] denotes 'word not found'
Well done so far with the content of your README file, however, to better the user of your application better understand how to navigate and use this application, you might want to go a bit into details on how to install, clone, contribute, and dependencies used admist others.

Also, you might want to also put an example file of what a valid file content should look like and examples of the result to expect from the two API endpoints when hit.

2017-05-10 16:40 UTC, andela-oaromokeye commented on dist/route/endpoints-validation.js
> +
Like i earlier mentioned, the bundled folder can be ignored

2017-05-10 16:40 UTC, andela-oaromokeye commented on src/inverted-index.js
> +    } else if (JSON.parse(fs.readFileSync(path.join('fixtures', fileName)))[0].title === undefined ||
For better code readablity, you can use and obey style guides

2017-05-10 16:40 UTC, andela-oaromokeye commented on src/inverted-index.js
>        for (let i = 0; i < searchTerms.length; i += 1) {
A forEach is preferred to a for loop when following best practices.

2017-05-10 16:40 UTC, andela-oaromokeye commented on tests/inverted-index-test.js
> +describe('create index endpoint', () => {
We always advice seperating concerns and you have a done a good jod with your test, however, you can better seperate instances by placing API test and Class test in different files

2017-05-11 17:59 UTC, merged